FROM archlinux AS builder
COPY files/ /
RUN pacman-key --init
RUN pacman -Syy --noconfirm archlinux-keyring
RUN pacman -Syu --noconfirm
RUN pacman --noconfirm -S docker \
                          docker-buildx \
                          git \
                          jq \
                          linux \
                          mdadm \
                          mkinitcpio \
                          xfsprogs

RUN systemctl enable gcpnetwork.service docker.service runner.service limit.timer localmount.service
RUN systemctl disable systemd-networkd systemd-timesyncd systemd-resolved
RUN useradd -m enf -G docker
RUN echo root:root | chpasswd

FROM archlinux AS buildfs
ARG ROOT_PART_SIZE
RUN mkdir /fs
COPY --from=builder / /fs
RUN rm /fs/boot/*
RUN truncate -s ${ROOT_PART_SIZE}MiB /rootfs.raw && mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 -d /fs /rootfs.raw

FROM scratch AS exportfs
COPY --from=buildfs /rootfs.raw /
COPY --from=builder /boot/arch.efi /
